[project]
name = "taskflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bakshish Kaur Arora", email = "88268292+BakshishArora@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
taskflow = "taskflow:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
